[build]
  command = "bun run build"
  publish = "public"

[build.environment]
  BUN_FLAGS = "--frozen-lockfile"
  BUN_VERSION = "1.3.8"
  NODE_VERSION = "22.22.2"

[dev]
  command = "bun run dev"
  publish = "public"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/assets-thumbnails/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
