---
backend:
  name: github
  repo: stephencookdev/moonfleetguesthouse
collections:
  - files:
      - fields:
          - label: Title
            name: title
          - label: Tagline
            name: tagline
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - field:
              label: Image
              name: image
              widget: image
            label: "Carousel images"
            name: carouselImage
            widget: list
          - label: Body
            name: body
            widget: markdown
        file: src/pages/index.md
        label: Homepage
        name: index
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - label: Tagline
            name: tagline
          - fields:
              - label: Name
                name: name
              - label: Tagline
                name: tagline
              - label: Short description
                name: shortDescription
                required: false
                widget: text
              - field:
                  label: Amenity
                  name: amenity
                label: Amenities
                name: amenities
                required: false
                widget: list
              - label: Normal price
                name: normalPrice
              - label: Saturday price
                name: saturdayPrice
              - label: Image
                name: image
                widget: image
              - label: Image alt
                name: imageAlt
                required: false
            label: Rooms
            name: rooms
            widget: list
          - label: Rooms extra
            name: roomsExtra
            widget: markdown
          - fields:
              - label: Title
                name: title
              - label: Body
                name: body
                widget: markdown
            label: "Extra sections"
            name: extraSections
            widget: list
        file: src/pages/room-rates.md
        label: Room rates
        name: room-rates
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - label: Section layout
            name: sectionLayout
            required: false
            widget: select
            options:
              - cards
              - article
          - fields:
              - label: Title
                name: title
              - label: Image
                name: image
                required: false
                widget: image
              - label: Image alt
                name: imageAlt
                required: false
              - label: Image caption
                name: imageCaption
                required: false
              - label: Body
                name: body
                widget: markdown
            label: "Pre-Map Sections"
            name: preMapSections
            widget: list
          - label: Google Maps IFrame SRC
            name: googleMapsIframeSrc
          - fields:
              - label: Title
                name: title
              - label: Image
                name: image
                required: false
                widget: image
              - label: Image alt
                name: imageAlt
                required: false
              - label: Image caption
                name: imageCaption
                required: false
              - label: Body
                name: body
                widget: markdown
            label: "Post-Map Sections"
            name: postMapSections
            widget: list
        file: src/pages/find-us.md
        label: "Find Us"
        name: find-us
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - fields:
              - label: Image
                name: image
                widget: image
              - label: Alt text
                name: alt
                required: false
              - label: Caption
                name: caption
                required: false
            label: Images
            name: images
            widget: list
        file: src/pages/gallery.md
        label: Gallery
        name: gallery
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - label: Section layout
            name: sectionLayout
            required: false
            widget: select
            options:
              - cards
              - article
          - fields:
              - label: Title
                name: title
              - label: Image
                name: image
                required: false
                widget: image
              - label: Image alt
                name: imageAlt
                required: false
              - label: Image caption
                name: imageCaption
                required: false
              - label: Body
                name: body
                widget: markdown
            label: "Sections"
            name: sections
            widget: list
        file: src/pages/contact-us.md
        label: "Contact Us"
        name: contact-us
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - label: Section layout
            name: sectionLayout
            required: false
            widget: select
            options:
              - cards
              - article
          - fields:
              - label: Title
                name: title
              - label: Image
                name: image
                required: false
                widget: image
              - label: Image alt
                name: imageAlt
                required: false
              - label: Image caption
                name: imageCaption
                required: false
              - label: Body
                name: body
                widget: markdown
            label: "Sections"
            name: sections
            widget: list
        file: src/pages/local-attractions.md
        label: "Things To Do"
        name: local-attractions
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - label: "Booking.com Rating"
            name: bookingComRating
          - label: "TripAdvisor Rating"
            name: tripAdvisorComRating
        file: src/pages/visitors-comments.md
        label: "Reviews"
        name: visitors-comments
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - fields:
              - label: Title
                name: title
              - label: Image
                name: image
                required: false
                widget: image
              - label: Image alt
                name: imageAlt
                required: false
              - label: Image caption
                name: imageCaption
                required: false
              - label: Body
                name: body
                widget: markdown
            label: "Sections"
            name: sections
            widget: list
        file: src/pages/dogs.md
        label: "Dogs"
        name: dogs
      - fields:
          - label: Title
            name: title
          - label: SEO title
            name: seoTitle
            required: false
          - label: SEO description
            name: seoDescription
            required: false
            widget: text
          - label: Canonical path
            name: canonicalPath
            required: false
          - label: Featured image
            name: featuredImage
            required: false
            widget: image
          - label: Featured image alt
            name: featuredImageAlt
            required: false
          - fields:
              - label: Title
                name: title
              - label: Image
                name: image
                required: false
                widget: image
              - label: Image alt
                name: imageAlt
                required: false
              - label: Image caption
                name: imageCaption
                required: false
              - label: Body
                name: body
                widget: markdown
            label: "Sections"
            name: sections
            widget: list
        file: src/pages/private-hire-group-accommodation-skinningrove.md
        label: "Private Hire"
        name: private-hire-group-accommodation-skinningrove
    label: Moonfleet Guesthouse
    name: moonfleet
  - create: true
    fields:
      - label: Title
        name: title
      - label: SEO title
        name: seoTitle
        required: false
      - label: SEO description
        name: seoDescription
        required: false
        widget: text
      - label: Canonical path
        name: canonicalPath
        required: false
      - label: Featured image
        name: featuredImage
        required: false
        widget: image
      - label: Featured image alt
        name: featuredImageAlt
        required: false
      - label: Section layout
        name: sectionLayout
        required: false
        widget: select
        options:
          - cards
          - article
      - fields:
          - label: Title
            name: title
          - label: Image
            name: image
            required: false
            widget: image
          - label: Image alt
            name: imageAlt
            required: false
          - label: Image caption
            name: imageCaption
            required: false
          - label: Body
            name: body
            widget: markdown
        label: "Sections"
        name: sections
        widget: list
    folder: src/pages/local-attractions
    label: "Local Guide Pages"
    name: local-guide-pages
    slug: "{{slug}}"
media_folder: static_assets
public_folder: /assets
